### ISSUE TITLE
Can't get Google assistant to launch paper signals

### ISSUE THREAD

**Issue by yaki4** [googlecreativelab/paper-signals#11]
Hi, i'm not sure that this is the right place to ask this but when i say to my assistant "talk to paper signals", he just respond with an internet link or some pictures of the project. 

Since i'm french, i tried the french version for this sentence or to write it down instead of saying it but it doesn't work either. 
Am i missing something ?

**Comment by nicolehe** [comment]
Hi @yaki4! Are you doing this on a Google Home or Google Assistant on your phone? If it's the Assistant, can you take a screenshot?

**Comment by yaki4** [comment]
I've tried it with both Google Home and Google Assistant. 
You can find the screenshots for the assistant below.
![capture _2017-12-07-14-11-58](https://user-images.githubusercontent.com/1856630/33735144-7081c13a-db5c-11e7-91ec-4a6f55e466fa.png)
![capture _2017-12-07-14-12-20](https://user-images.githubusercontent.com/1856630/33735145-7090f5c4-db5c-11e7-8294-2af6563b0d62.png)

**Comment by nicolehe** [comment]
Unfortunately, because Paper Signals is only supported in English at this time, if your language settings are in French, you won't be able to use the app. If you switch your language settings to English, it should work. Sorry!

**Comment by yaki4** [comment]
Oh yeah that make sense. 

Thanks for your response and this great experiment.
