### ISSUE TITLE
Countdown Timer - Not Couting

### ISSUE THREAD

**Issue by nick-at** [googlecreativelab/paper-signals#13]
Have set up a countdown signal following all the instructions. When I set a timer, the servo moves to 180*, to 0*, stops, stays there and begins to heat up. This is my first arduino project and am not sure where to begin to troubleshoot!

Have tried counting down to a date and even for 30 seconds - same result for all.

**Comment by dfashbaugh** [comment]
Hey @nick-at, does the servo move away from that position when you restart the signal? Sometimes the cheaper plastic geared servos can have issues at the extreme ends of their motion.

To test if this is the issue, you can open APICalls.h and make the Timer positions less extreme. The code below can just be copied and pasted into that file in place of the current timer position code.

// Timer
#define TIMER_START 30
#define TIMER_END 150
#define TIMER_WIGGLE_TOP 30
#define TIMER_WIGGLE_BOTTOM 150
