### ISSUE TITLE
Three word identifier from Google Assistant

### ISSUE THREAD

**Issue by mactishp** [googlecreativelab/paper-signals#21]
Hi,

I am trying out this project but I get stuck retrieving the three word identifier from Google Assistant as described in the steps. (it doesn't work) I attached a screenshot of this step. Can anybody help me with this?
![screen shot 2017-12-22 ps](https://user-images.githubusercontent.com/35067774/34521959-b45b6138-f090-11e7-845c-9de93a7c48f6.png)

**Comment by nicolehe** [comment]
Hi @mactishp, can you tell me what it says when you're trying?

**Comment by mactishp** [comment]
Hi @nicolehe, 
It simply returns a link to gitHub. (see attached screenshot)
Some sidenotes maybe: I'm trying it on IOS with the Google Allo app (where Google Assistant is integrated in)
![googleassistantiosscreenshot](https://user-images.githubusercontent.com/35067774/34526878-0b1210e0-f0a4-11e7-90d8-458dc5aa9c9c.jpg)

**Comment by nicolehe** [comment]
Are you already in the Paper Signals app?

Can you try this:

"Talk to Paper Signals."
and then:
"Create a new signal."

**Comment by mactishp** [comment]
I can't follow you there. What do mean with the Paper Signals app? Isn't that just Google Assistant?
In Google Assistant I tried those 2 sentences as is described in the step but Google Assistant just returns a link to a webpage.

**Comment by nicolehe** [comment]
Yes - within the Google Assistant, can you try saying "Talk to Paper Signals" and then send a screenshot?

**Comment by mactishp** [comment]
Here you go:
![googleassistantscreenshotps](https://user-images.githubusercontent.com/35067774/34527568-3df4253c-f0a6-11e7-88e2-47d993dd75c6.jpg)

**Comment by nicolehe** [comment]
Okay, I think this is the same issue as #11 - is your Assistant set to a language that's not English? Paper Signals is only supported in English, so if your Assistant is set to a different language it won't be able to access it.

**Comment by mactishp** [comment]
Sounds logically. But unfortunately, I was already corresponding in English with Google Assistant since Google Assistant doesn't support my country language (Dutch). I even put my phones language to English, reinstalled Google Assistant but it still doesn't work.

**Comment by nicolehe** [comment]
Hmm....does it still say "Zeg iets..." when you set the Assistant to English?

**Comment by mactishp** [comment]
No, even that is English now.

**Comment by nicolehe** [comment]
Do you mind sending another screenshot saying "Talk to Paper Signals" with the app in English?

**Comment by mactishp** [comment]
![googleassistantscreenshotps2](https://user-images.githubusercontent.com/35067774/34528780-3e814922-f0aa-11e7-9d0a-031552fe2300.jpg)

**Comment by nicolehe** [comment]
Thanks, I'll look into it and get back to you.

**Comment by KOstasHatzis** [comment]
Try to write the message instead. Let's see what happens...

**Comment by mactishp** [comment]
Oh yeah, I got tired a while a go of using the speaking option :D So I was writing the message all this time. I assumed it would/should not make a difference? 
But now I've tried both (speaking/writing) and it gives the same as last screenshot shows. 
It would be nice if you could find what isn't working here since we intend to use this project in a larger marketing workshops towards our customers ;)

**Comment by KOstasHatzis** [comment]
Kill the app and install it again. Now that you have the language in English.

**Comment by KOstasHatzis** [comment]
I assume from the screenshots that you work on an android phone, right?

**Comment by mactishp** [comment]
Yeah, I already reinstalled it (see 4 posts back) but did it again anyways. But no change. 
No, I'm trying it on IOS iPhone.

**Comment by KOstasHatzis** [comment]
I have 2 languages in my mob too. Greek and English. And it works just fine.

**Comment by mactishp** [comment]
@nicolehe , it still isn"t functioning, any new solutions maybe?

**Comment by jduitsman** [comment]
@nicolehe   I have the same issue. Only getting links to website's and no unique 3-word identifier. Tried everything.

App is in English, writing, speaking, on phone, on mac etc etc. can't getting it to work. ;-((

**Comment by nicolehe** [comment]
Hi @mactishp, @jduitsman, apologies for the long delay. Finally got confirmation that this is not currently supported in the Netherlands. The language when you try to invoke the app should now reflect that. Sorry about that!

**Comment by mactishp** [comment]
Half a year later is a little bit too late for me...
Btw, it’s Belgium, not The Netherlands.

**Comment by muthhus** [comment]
I am getting same issue and unable to move further. I can't get 3-word identifier and Also I am getting the following error.
![screen shot 2019-01-19 at 17 51 12](https://user-images.githubusercontent.com/84474/51430389-d3358580-1c12-11e9-9320-96364c01a82e.png)

**Comment by cipiger** [comment]
How about the usage in Germany? I do have the same problem, although I changed my language settings to englisch (us).

**Comment by lromor** [comment]
I have the same issue. Any news?

**Comment by cipiger** [comment]
Sorry, nio. This google service was not supported in germany.
 

Gesendet: Montag, 18. Januar 2021 um 16:34 Uhr
Von: "Leonardo Romor" <notifications@github.com>
An: "googlecreativelab/paper-signals" <paper-signals@noreply.github.com>
Cc: "cipiger" <olaf.cimanowski@web.de>, "Comment" <comment@noreply.github.com>
Betreff: Re: [googlecreativelab/paper-signals] Three word identifier from Google Assistant (#21)


 

I have the same issue. Any news?

**Comment by michaelshorter** [comment]
Hi all,

I'm also having the exact same problem. Running Google Assistant in English and in the UK. Has anyone got to the bottom of this yet?
