### ISSUE TITLE
Alternate Hardware 

### ISSUE THREAD

**Issue by sarrocks1** [googlecreativelab/paper-signals#25]
Can a NODEMCU ESP8266 be used in place of AdaFruit Feather Huzzah ??
link to the NodeMcu  - https://www.amazon.in/Lolin-NodeMCU-3-01-0268-1-NodeMCU-WiFi-Arduino-IDE-Lua-based-IoT-ESP8266-Development-Board/dp/B010O1G1ES?tag=googinhydr18418-21&tag=googinkenshoo-21&ascsubtag=d893498e-f613-4253-802f-d760ead0ce17
I mean to ask are both of them same??

**Comment by dfashbaugh** [comment]
Yes, this can be used. Its not exactly the same, but the differences shouldn't affect Paper Signals! You will still be able to upload the code using the Huzzah board in Arduino.

**Comment by sarrocks1** [comment]
@dfashbaugh  Thank You!!
