### ISSUE TITLE
DynamicJsonBuffer Issue

### ISSUE THREAD

**Issue by ghost** [googlecreativelab/paper-signals#27]
I followed all the directions when on Connect your Paper Signal when I got to step 7 and I tried to upload I got an error proclaiming

> 'DynamicJsonBuffer' was not declared in this scope

wonder what I did wrong, a or more likely what information might be usefull in solving this

**Comment by dfashbaugh** [comment]
Hey @levimail12 , Looks like ArduinoJSON released a new version that is not compatible with Paper Signals at the moment. To get compiling, you'll need to rollback a version.

To do this, Open up Arduino. Then go to Sketch->Include Library->Manage Libraries...

Then search for ArduinoJSON.

When you find the library, just use the drop down in the bottom left to select a slightly older version and click "Update."

![image](https://user-images.githubusercontent.com/6462861/41186507-aa8aef98-6b65-11e8-8fbe-c92ee6eb012e.png)

**Comment by mattboh9** [comment]
Is this still a problem because I’m having a similar situation that when I get to step 7 I get a compile error.
