### ISSUE TITLE
Can't get Google Assistant/Paper Signals Link Completed

### ISSUE THREAD

**Issue by tomvdb** [googlecreativelab/paper-signals#4]
Got my countdown paper signal built, setting up the code. Next step is getting the unique 3-word identifier. Google assistant takes me to paper signal that tells me about the paper signal website and then asks me do I want to build a countdown,pants, etc. When I reply, it just sits there until google assistant comes back and says that paper signals isn't responding right now, please try again soon :(

**Comment by dfashbaugh** [comment]
Is this happening to you every time you try? Or does the issue seem intermittent?

**Comment by dfashbaugh** [comment]
Sorry, didn't mean to close the issue!
Anyway, I have not been able to recreate the problem. So any more information would be very helpful!

**Comment by tomvdb** [comment]
I did that for a long time, and then it just started working. The setup was a bit nightmarish and found a few bugs, but will start another issue for those.

Thanks,
