### ISSUE TITLE
connecting to gweb-paper-signals.firebaseio.com failed

### ISSUE THREAD

**Issue by mintisan** [googlecreativelab/paper-signals#8]
I use my iPhone as a hotspot, and I can connect to `console.firebase.google.com` with my iPhone(use shadowsocks to connect to Google).

![image](https://user-images.githubusercontent.com/9136049/33561765-85097d1a-d94e-11e7-8865-a2687038c657.png)
![image](https://user-images.githubusercontent.com/9136049/33561784-93a331a4-d94e-11e7-8f75-5b26d7646dbc.png)

ESP8266 UART message showed that WiFi connection is fine.
```
............
WiFi connected
IP address: 172.20.10.2
connecting to gweb-pape
```

but  I can't connect to firebase  as below:
```
connecting to gweb-paper-signals.firebaseio.com
connection failed
parseObject() failed
Default
```

![image](https://user-images.githubusercontent.com/9136049/33561357-69c104ca-d94d-11e7-9f8c-e512400ce211.png)

Did I miss any settings? 

My modification of code is just as below:

![image](https://user-images.githubusercontent.com/9136049/33561308-4a1e2904-d94d-11e7-98e5-88f24d28092e.png)

**Comment by tomvdb** [comment]
Not sure if it's the same, but I had the same problem. The esp8266 calls this url:

`https://gweb-paper-signals.firebaseio.com/signals/your-signalid-here.json`

if your unique id is wrong, then it just returns null, instead of a valid json object so you then get the parseObject() error in the debug log.

Does 

`https://gweb-paper-signals.firebaseio.com/signals/politely-appellate-hippopotamus.json `

return valid json data if you check it in a browser or just say null?

Nevermind, I checked it with your id in the browser and it does return data. Must be something else then

**Comment by dfashbaugh** [comment]
@mintisan Does the system spend a long time at the "connecting to gweb-paper-signals.firebaseio.com" or does it seem to immediately fail?

When you're connected to your phone hotspot with another computer are you able to see the JSON data from: https://gweb-paper-signals.firebaseio.com/signals/politely-appellate-hippopotamus.json

I'm not totally familiar with Shadowsocks. But your setup looks good to me so far.

As @tomvdb noted above, there is definitely data at your signal ID URL.

**Comment by mintisan** [comment]
@tomvdb Yes, I can open [URL](https://gweb-paper-signals.firebaseio.com/signals/politely-appellate-hippopotamus.json) on my iPhone which acted as proxy. 

And I will check its return value on ESP8266 with UART log.

Thanks.

**Comment by mintisan** [comment]
@tomvdb  @dfashbaugh  Maybe I find the reason why  I can't access [URL](https://gweb-paper-signals.firebaseio.com/signals/your-signalid-here.json) for ESP8266.( I can open URL on my iPhone.)

So the proxy configuration need to be modified for hotspot.

I will have a try firstly ...

Thanks so much, @tomvdb  @dfashbaugh

**Comment by Wanguy** [comment]
Perhaps It can't connect to `console.firebase.google.com` while using your hotspot. Although you can open the URL on your phone which acted as the proxy when you share your hotspot.

**Comment by mintisan** [comment]
After I changed the configuration. It works for me now. :D

```
P address: 172.24.1.23
connecting to gweb-paper-signals.firebaseio.com
requesting URL /signals/politely-appellate-hippopotamus.json
request sent
HTTP/1.1 200 OK

Server: nginx

Date: Sat, 09 Dec 2017 07:39:41 GMT

Content-Type: application/json; charset=utf-8

Content-Length: 503

Connection: close

Access-Control-Allow-Origin: *

Cache-Control: no-cache

Strict-Transport-Security: max-age=31556926; includeSubDomains; preload



headers received
Timer: 30
```

**Comment by nicolehe** [comment]
Glad it's working @mintisan! I'd recommend deleting this signal and creating a new one with a new unique ID for security reasons. :)
